baseurl = "http://mantzas.github.io/"
title = "Coding Odyssey"
languageCode = "en-us"
disqusShortname = "mantzas" # Optional, enable Disqus integration
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Sotirios Mantziaris"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"
	
#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Your default page description"
    defaultKeywords = "your,default,page,keywords"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    # theme = "theme-base-09"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    # highlight = "highlight"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Coding Odyssey"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    # googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-69796473-2"
    gravatarHash = "ebf5e759c2227c59a1ee8233fcccc0c4"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/mantzas"
    # bitbucket = "https://bitbucket.org/mantzas"
    stackOverflow = "http://stackoverflow.com/users/182740/mantzas"
    linkedin = "https://gr.linkedin.com/in/sotirismantziaris"
    # googleplus = ""
    # facebook = ""
    twitter = "https://twitter.com/SMantziaris"
    # youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    # flattr = ""  # populate with your flattr uid